### ISSUE TITLE
HTML being passed unescaped in messages (page, say, etc.)

### ISSUE THREAD

**Issue by Mirrdae** [mucklet/mucklet-client#123]
Discovered just a few minutes ago.  HTML is being passed unescaped in messages.  Tested in page and say.
Ampersand ( & ) also affected.

Reproduction steps:
```HTML
say This <h2>is in heading 2</h2>.
```
Also have been able to use <button>  tags.  Of particular concern, javascript can be embedded in event handlers as part of the tag such as onclick="alert('yallo!')".

Suggested resolution:
Angle brackets < and >, as well as & and other special HTML characters should be escaped or HTML encoded somehow.

**Comment by AlyxAlyx** [comment]
Private vulnerability reporting should probably be enabled for this project, high severity issues in a public place is a field day for bad actors.

**Comment by anisus** [comment]
@AlyxAlyx , I can agree to that thought. I'll look  into it how that can be improved.

But the bug is resolved in PR #124 , and included in the patch release v1.50.1 (1ffb86d15194ec5bf545f8ec61bdb399d602b4e6).
