### ISSUE TITLE
Exclude muted characters from autocompletion

### ISSUE THREAD

**Issue by Warphammer** [mucklet/mucklet-client#133]
As part of or an adjunct to disambiguation of tab completion, a thought: If you have someone muted you're not talking to them. Removing the ability to accidentally tab-complete their name in, say a whisper might be a nice thing to do.

**Comment by anisus** [comment]
I agree with this one.
You shouldn't autocomplete to someone muted. Thanks for the suggestion!

**Comment by anisus** [comment]
Resolved in PR #144
