### ISSUE TITLE
Can't authenticate to test realm from localhost

### ISSUE THREAD

**Issue by ItsAKelmi** [mucklet/mucklet-client#269]
Not sure when this started, but trying to authenticate into a local dev environment for the client with the method in the [Quick Start in README.md](https://github.com/mucklet/mucklet-client?tab=readme-ov-file#quick-start) seems to now fail due to an origin check somewhere on the server side.

![image](https://github.com/mucklet/mucklet-client/assets/161910439/95a24636-0c7a-4825-a2b0-a89f42908245)

The websocket connection dies with:
```{"error":{"code":"auth.unsafeOrigin","message":"Not allow from unsafe origin."},"id":2}```

**Comment by ItsAKelmi** [comment]
@anisus Just checking in. Is this something that is likely to get resolved in the near future?

**Comment by anisus** [comment]
Sorry for the radio silence, @ItsAKelmi ! I am trying to get back on things now. I went in and fixed the configuration, so you should be able to connect from localhost now.
I will close this once confirmed that it is working for you as well.

**Comment by ItsAKelmi** [comment]
Seems to be working now. Thank you!
