### ISSUE TITLE
Preview of text formatting

### ISSUE THREAD

**Issue by anisus** [mucklet/mucklet-client#32]
## Issue

When typing formatted text in the console, such as a pose or a say message, the text formatting should be previewed directly while typing the command in the console.

See these Wolfery Forum discussions:
https://forum.wolfery.com/t/feature-suggestion-preview-of-bold-cursive-etc/1623/3
https://forum.wolfery.com/t/change-of-colour-ic-vs-ooc/2157

## Notes

* The formatting should be for inline formatting like `**bold**`, `_italics_`, `((ooc))` and similar.
* The formatting should preferably indicate if the message is ooc: `:>types an ooc pose`
* In the console, all typed characters should show (Eg. when typing `**bold**`, the asterisks should show in the console, even if they won't appear in the chat log after being sent.)

**Comment by xetem** [comment]
I've been looking into this one today. May not be a quick implementation, but I think I'm on the right track.

**Comment by anisus** [comment]
@xetem  Neat! I check your branch, and I think that is a good first step, to enable Codemirror to add those decorations.
Now (if I understand your addition correctly), it will be about either expanding `TextStep`  to have the option of emitting those tokens (`bold`, `italics`, `ooc`, etc.) based on our formatting rules (as "defined" in `formatText.js`).

Or maybe instead of expanding TextStep, to create a similar `FormatTextStep`.

But I can understand if the parser system can feel a bit complex.

**Comment by anisus** [comment]
I've been looking closer into this.
It seems we will run into an issue with the current parser, as it only does line-by-line parsing. The problem is that some formatting, like `_italics_` is allowed to span over multiple lines:
```text
_this text
will also be written with italics_
```

But in order for the parser to know that "this text" should be in italics, the parser needs to check if there is a matching end `_` on some other line. And... we can't do that now.

I see a couple of options:

Instead of using StreamParser, writing our own custom parser as suggested in this CodeMirror topic:
https://discuss.codemirror.net/t/writing-a-custom-parser-without-using-lezer-or-streamparser/4692

Another option is to rid ourselves with CodeMirror overall. Not sure how viable that is though.

**Comment by xetem** [comment]
No worries here 😁 I too was actually looking into hooking into formatText.js, but tried doing so without changing anything about it and hit a wall. 😅
