### ISSUE TITLE
Inactive room exits

### ISSUE THREAD

**Issue by anisus** [mucklet/mucklet-client#329]
Issue

It should be possible to set an exit as inactive. An inactive exit should not show up, except for the list of hidden exits when editing. It should also not be possible to use the exit.

The primary purpose for inactive exits is to allow room scripts to toggle them active/inactive, as well as to be used for redirect exit usage.

**Comment by GreenReaper** [comment]
So my cable car can enable its exit when it arrives in the station (and the one for the relevant station inside)? Useful. 😼

**Comment by anisus** [comment]
@GreenReaper , exactly for such purposes. But it will also be possible for a room script to intercept someone trying to use an exit, and redirect them to one of the inactive exits, to make exits with multiple possible targets. May be useful for puzzles or randomized exits.

**Comment by anisus** [comment]
Resolved in PR #330
